In [1]:
import numpy as np
import torch
import torch.nn.functional as F

# Define the 5x5 input matrix

input_matrix = np.array([
    [1,  2,  3,  4,  5],
    [6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)

# Define the 3x3 Kernel

kernel = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
], dtype=np.float32)

# Convolution Operations
x = torch.tensor(input_matrix).unsqueeze(0).unsqueeze(0) # Input  = [batch, channels, height, width]

k = torch.tensor(kernel).unsqueeze(0).unsqueeze(0)   # Kernel = [out_channels, in_channels, height, width]

print("\n================ PYTORCH RESULTS ================\n")

# Case 1: Stride = 1, VALID

output_valid_s1 = F.conv2d(
    x,
    k,
    stride=1,
    padding=0
)

print("Stride = 1, Padding = VALID")
print(output_valid_s1.squeeze())

# CASE 2: Stride = 1, SAME

output_same_s1 = F.conv2d(
    x,
    k,
    stride=1,
    padding="same"
)

print("\nStride = 1, Padding = SAME")
print(output_same_s1.squeeze())

# CASE 3: Stride = 2, VALID

output_valid_s2 = F.conv2d(
    x,
    k,
    stride=2,
    padding=0
)

print("\nStride = 2, Padding = VALID")
print(output_valid_s2.squeeze())



""" CASE 4: Stride = 2, SAME
PyTorch does NOT allow:
F.conv2d(..., stride=2, padding="same")
Therefore SAME padding is performed manually.
For a 5x5 input, 3x3 kernel, stride 2:
Output size = ceil(5/2) = 3
Required padding = 1 on each side"""

x_same_s2 = F.pad(
    x,
    (1, 1, 1, 1)
)

output_same_s2 = F.conv2d(
    x_same_s2,
    k,
    stride=2,
    padding=0
)

print("\nStride = 2, Padding = SAME")
print(output_same_s2.squeeze())


================ PYTORCH RESULTS ================

Stride = 1, Padding = VALID
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Stride = 1, Padding = SAME
tensor([[  4.,   3.,   2.,   1.,  -6.],
        [ -5.,   0.,   0.,   0., -11.],
        [-10.,   0.,   0.,   0., -16.],
        [-15.,   0.,   0.,   0., -21.],
        [-46., -27., -28., -29., -56.]])

Stride = 2, Padding = VALID
tensor([[0., 0.],
        [0., 0.]])

Stride = 2, Padding = SAME
tensor([[  4.,   2.,  -6.],
        [-10.,   0., -16.],
        [-46., -28., -56.]])
